
export const onlineServicesPageMockData = {
  services: [
    {
      id: 'psn-001',
      name: 'playstation',
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '3 month',
        fees: {
          monthly: '$6.66',
          quarterly: '$18.99',
          annual: '$66.66',
        },
        renewalDate: {
          day: '1',
          month: 'January',
        },
        paymentMethod: 'Visa',
      },
      tier: {
        name: 'essential', // from "tierName"
        features: ['Online Play', 'Monthly Games', 'Cloud Storage'],
      },
      features: ['Cross-Platform Play', 'Cloud Saves', 'Member Discounts'],
      label: 'Playstation Network',
      logo: 'playstation',
      url: 'https://www.playstation.com/en-us/playstation-network/',
    },
    {
      id: 'xbox-002',
      name: 'xbox',
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 month',
        fees: {
          monthly: '$14.99',
          quarterly: '$44.97',
          annual: '$139.92',
        },
        renewalDate: {
          day: '15',
          month: 'March',
        },
        paymentMethod: 'Mastercard',
      },
      tier: {
        name: 'Game Pass Standard',
        features: ['Game Pass Library', 'Xbox Live Gold', 'Exclusive Discounts'],
      },
      features: ['Cloud Gaming', 'Cross-Platform Play', 'Member Perks'],
      label: 'Xbox Network',
      logo: 'xbox',
      url: 'https://www.xbox.com/en-US/xbox-game-pass',
    },
    {
      id: 'nintendo-003',
      name: 'nintendo',
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 year',
        fees: {
          monthly: '$3.99',
          quarterly: '$11.97',
          annual: '$34.96',
        },
        renewalDate: {
          day: '1',
          month: 'January',
        },
        paymentMethod: 'Visa',
      },
      tier: {
        name: 'Switch Online',
        features: ['Online Play', 'Classic Game Library'],
      },
      features: ['Cloud Saves', 'Smartphone App', 'Special Offers'],
      label: 'Nintendo Switch Online',
      logo: 'nintendo',
      url: 'https://www.nintendo.com/us/switch/online/',
    },
    {
      id: 'steam-004',
      name: 'steam',
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: 'NA',
        fees: {
          monthly: 'FREE',
          quarterly: 'FREE',
          annual: 'FREE',
        },
        renewalDate: {
          day: 'NA',
          month: 'NA',
        },
        paymentMethod: 'Paypal',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['Achievements', 'Cloud Saves', 'Workshop Support'],
      label: 'Steam',
      logo: 'steam',
      url: 'https://store.steampowered.com',
    },
    {
      id: 'epic-005',
      name: 'epicgames',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: 'NA',
        fees: {
          monthly: 'FREE',
          quarterly: 'FREE',
          annual: 'FREE',
        },
        renewalDate: {
          day: 'NA',
          month: 'NA',
        },
        paymentMethod: 'Alipay',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['Free Weekly Games', 'Cloud Saves', 'Cross-Platform Support'],
      label: 'Epic Games Store',
      logo: 'epic',
      url: 'https://store.epicgames.com/en-US/',
    },
    {
      id: 'gog-006',
      name: 'gog',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: 'NA',
        fees: {
          monthly: 'FREE',
          quarterly: 'FREE',
          annual: 'FREE',
        },
        renewalDate: {
          day: 'NA',
          month: 'NA',
        },
        paymentMethod: 'Jcb',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['DRM-Free Games', 'Cloud Saves', 'Game Backups'],
      label: 'GOG.com',
      logo: 'gog',
      url: 'https://www.gog.com/games',
    },
    {
      id: 'humble-007',
      name: 'humble',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 year',
        fees: {
          monthly: '$11.99',
          quarterly: '$35.97',
          annual: '$129',
        },
        renewalDate: {
          day: '1',
          month: 'January',
        },
        paymentMethod: 'Paypal',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['Monthly Bundles', 'Store Discounts', 'Charity Donations'],
      label: 'Humble Bundle',
      logo: 'humble',
      url: 'https://www.humblebundle.com/',
    },
    {
      id: 'greenman-008',
      name: 'greenman',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: 'NA',
        fees: {
          monthly: 'FREE',
          quarterly: 'FREE',
          annual: 'FREE',
        },
        renewalDate: {
          day: 'NA',
          month: 'NA',
        },
        paymentMethod: 'Visa',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['PC Game Store', 'Deals and Discounts'],
      label: 'Green Man Gaming',
      logo: 'greenman',
      url: 'https://www.greenmangaming.com/',
    },
    {
      id: 'fanatical-009',
      name: 'fanatical',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: 'NA',
        fees: {
          monthly: 'FREE',
          quarterly: 'FREE',
          annual: 'FREE',
        },
        renewalDate: {
          day: 'NA',
          month: 'NA',
        },
        paymentMethod: 'Amex',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['Bundled Deals', 'Storefront Discounts'],
      label: 'Fanatical',
      logo: 'fanatical',
      url: 'https://www.fanatical.com/',
    },
    {
      id: 'apple-arcade-010',
      name: 'applearcade',
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 month',
        fees: {
          monthly: '$6.99',
          quarterly: '$20.97',
          annual: '$49.99',
        },
        renewalDate: {
          day: '1',
          month: 'August',
        },
        paymentMethod: 'Mastercard',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['No Ads', 'Family Sharing', 'Offline Play'],
      label: 'Apple Arcade',
      logo: 'apple',
      url: 'https://www.apple.com/apple-arcade/',
    },
    {
      id: 'netflix-games-011',
      name: 'netflixgames',
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 year',
        fees: {
          monthly: '$15.49',
          quarterly: '$46.47',
          annual: '$139.41',
        },
        renewalDate: {
          day: '1',
          month: 'January',
        },
        paymentMethod: 'Visa',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['Mobile Games Catalog', 'Ad-Free Gaming'],
      label: 'Netflix Games',
      logo: 'netflix',
      url: 'https://www.netflix.com/',
    },
    {
      id: 'geforce-012',
      name: 'geforce',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 year',
        fees: {
          monthly: '$4.99',
          quarterly: '$17.97',
          annual: '$59.94',
        },
        renewalDate: {
          day: '1',
          month: 'February',
        },
        paymentMethod: 'Alipay',
      },
      tier: {
        name: 'priority',
        features: ['Priority Queue', 'Extended Session Length'],
      },
      features: ['Cloud Gaming', 'RTX On', 'Cross-Platform'],
      label: 'GeForce Now',
      logo: 'nvidia',
      url: 'https://www.nvidia.com/en-us/geforce/products/geforce-now/',
    },
    {
      id: 'prime-gaming-013',
      name: 'primegaming',
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 year',
        fees: {
          monthly: '$14.99',
          quarterly: '$44.97',
          annual: '$139.92',
        },
        renewalDate: {
          day: '1',
          month: 'March',
        },
        paymentMethod: 'Visa',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['Free PC Games', 'In-Game Loot', 'Twitch Subscription'],
      label: 'Prime Gaming',
      logo: 'prime',
      url: 'https://www.amazongames.com/en-us/support/prime-gaming/articles/what-is-prime-gaming',
    },
    {
      id: 'play-pass-014',
      name: 'playpass',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 month',
        fees: {
          monthly: '$5.99',
          quarterly: '$17.97',
          annual: '$59.94',
        },
        renewalDate: {
          day: '1',
          month: 'August',
        },
        paymentMethod: 'Discover',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['Ad-Free Apps', 'Family Sharing'],
      label: 'Google Play Pass',
      logo: 'playpass',
      url: 'https://play.google.com/intl/en_us/about/play-pass/',
    },
    {
      id: 'ea-play-015',
      name: 'eaplay',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 year',
        fees: {
          monthly: '$5.99',
          quarterly: '$17.97',
          annual: '$59.94',
        },
        renewalDate: {
          day: '1',
          month: 'August',
        },
        paymentMethod: 'Mastercard',
      },
      tier: {
        name: '',
        features: [],
      },
      features: ['Early Trials', 'Game Library', 'Member Discounts'],
      label: 'EA Play',
      logo: 'ea',
      url: 'https://www.ea.com/en-us/games/ea-play',
    },
    {
      id: 'quest-plus-016',
      name: 'quest+',
      status: 'inactive',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      type: 'GAMING',
      billing: {
        cycle: '1 year',
        fees: {
          monthly: '$7.99',
          quarterly: '$23.97',
          annual: '$59.94',
        },
        renewalDate: {
          day: '1',
          month: 'August',
        },
        paymentMethod: 'Amex',
      },
      tier: {
        name: 'monthly',
        features: ['Two Free VR Games / Month'],
      },
      features: ['VR Game Discounts', 'App Lab Access'],
      label: 'Meta Quest+',
      logo: 'meta',
      url: 'https://www.meta.com/questplus',
    },
  ],
  totalServices: 16,
};

// export const onlineServicesPageMockData: OnlineServicesData = {
//   services: [
//     {
//       name: 'playstation',
//       label: 'Playstation Network',
//       logo: 'playstation',
//       tierName: 'essential', // Essential, Extra, Premium
//       url: 'https://www.playstation.com/en-us/playstation-network/',
//       billingCycle: '3 mo', // 1mo, 3mo, 1yr
//       monthlyFee: '$6.66',
//       quarterlyFee: '$18.99',
//       annualFee: '$66.66',
//       renewalDay: '1',
//       renewalMonth: 'January',
//       isActive: true,
//       paymentMethod: 'Visa',
//       plan: '3 month',
//     },
//     {
//       name: 'xbox',
//       label: 'Xbox Network',
//       logo: 'xbox',
//       tierName: 'Game Pass Standard', // PC Game Pass, Game Pass Core, Game Pass Standard, Game Pass Ultimate
//       url: 'https://www.xbox.com/en-US/xbox-game-pass',
//       billingCycle: '1 mo',
//       monthlyFee: '$14.99',
//       quarterlyFee: '$44.97',
//       annualFee: '$139.92',
//       renewalDay: '15',
//       renewalMonth: 'March',
//       isActive: true,
//       paymentMethod: 'Mastercard',
//       plan: '1 month',
//     },
//     {
//       name: 'nintendo',
//       label: 'Nintendo Switch Online',
//       logo: 'nintendo',
//       tierName: 'Switch Online', // Switch Online, Switch Online + Expansion Pack
//       url: 'https://www.nintendo.com/us/switch/online/',
//       billingCycle: '1 yr',
//       monthlyFee: '$3.99',
//       quarterlyFee: '$11.97',
//       annualFee: '$34.96',
//       renewalDay: '1',
//       renewalMonth: 'January',
//       isActive: true,
//       paymentMethod: 'Visa',
//       plan: '1 month',
//     },
//     {
//       name: 'steam',
//       label: 'Steam',
//       logo: 'steam',
//       tierName: '', // No tier
//       url: 'https://store.steampowered.com',
//       billingCycle: 'NA',
//       monthlyFee: 'FREE',
//       quarterlyFee: 'FREE',
//       annualFee: 'FREE',
//       renewalDay: 'NA',
//       renewalMonth: 'NA',
//       isActive: true,
//       paymentMethod: 'Paypal',
//       plan: '',
//     },
//     {
//       name: 'epicgames',
//       label: 'Epic Games Store',
//       logo: 'epic',
//       tierName: '',
//       url: 'https://store.epicgames.com/en-US/',
//       billingCycle: 'NA',
//       monthlyFee: 'FREE',
//       quarterlyFee: 'FREE',
//       annualFee: 'FREE',
//       renewalDay: 'NA',
//       renewalMonth: 'NA',
//       isActive: false,
//       paymentMethod: 'Alipay',
//       plan: '',
//     },
//     {
//       name: 'gog',
//       label: 'GOG.com',
//       logo: 'gog',
//       tierName: '',
//       url: 'https://www.gog.com/games',
//       billingCycle: 'NA',
//       monthlyFee: 'FREE',
//       quarterlyFee: 'FREE',
//       annualFee: 'FREE',
//       renewalDay: 'NA',
//       renewalMonth: 'NA',
//       isActive: false,
//       paymentMethod: 'Jcb',
//       plan: '12 month',
//     },
//     {
//       name: 'humble',
//       label: 'Humble Bundle',
//       logo: 'humble',
//       tierName: '',
//       url: 'https://www.humblebundle.com/',
//       billingCycle: '1 yr', // 1 mo - $11.99, 1 yr - $129
//       monthlyFee: '$11.99',
//       quarterlyFee: '$35.97',
//       annualFee: '$129',
//       renewalDay: '1',
//       renewalMonth: 'January',
//       isActive: false,
//       paymentMethod: 'Paypal',
//       plan: '',
//     },
//     {
//       name: 'greenman',
//       label: 'Green Man Gaming',
//       logo: 'greenman',
//       tierName: '', // Unknown - requires research
//       url: 'https://www.greenmangaming.com/',
//       billingCycle: 'NA',
//       monthlyFee: 'FREE',
//       quarterlyFee: 'FREE',
//       annualFee: 'FREE',
//       renewalDay: 'NA',
//       renewalMonth: 'NA',
//       isActive: false,
//       paymentMethod: 'Visa',
//       plan: '',
//     },
//     {
//       name: 'fanatical',
//       label: 'Fanatical',
//       logo: 'fanatical',
//       tierName: '', // Unknown - requires research
//       url: 'https://www.fanatical.com/',
//       billingCycle: 'NA',
//       monthlyFee: 'FREE',
//       quarterlyFee: 'FREE',
//       annualFee: 'FREE',
//       renewalDay: 'NA',
//       renewalMonth: 'NA',
//       isActive: false,
//       paymentMethod: 'Amex',
//       plan: '',
//     },
//     {
//       name: 'applearcade',
//       label: 'Apple Arcade',
//       logo: 'apple',
//       tierName: '', // monthly, yearly
//       url: 'https://www.apple.com/apple-arcade/',
//       billingCycle: '1 mo',
//       monthlyFee: '$6.99',
//       quarterlyFee: '$20.97',
//       annualFee: '$49.99',
//       renewalDay: '1',
//       renewalMonth: 'August',
//       isActive: true,
//       paymentMethod: 'Mastercard',
//       plan: '1 month',
//     },
//     {
//       name: 'netflixgames',
//       label: 'Netflix Games',
//       logo: 'netflix',
//       tierName: '', // standardads - $6.99, standard - $15.49, premium - $22.99
//       url: 'https://www.netflix.com/',
//       billingCycle: '1 yr',
//       monthlyFee: '$15.49',
//       quarterlyFee: '$46.47',
//       annualFee: '$139.41',
//       renewalDay: '1',
//       renewalMonth: 'January',
//       isActive: true,
//       paymentMethod: 'Visa',
//       plan: '1 month',
//     },
//     {
//       name: 'geforce',
//       label: 'GeForce Now',
//       logo: 'nvidia',
//       tierName: 'priority', // 1-month: free (add supported), Performance - 9.99, Ultimate - 19.99 // 6-month: Free, Performance - 49.99, Ultimate - 99.99
//       url: 'https://www.nvidia.com/en-us/geforce/products/geforce-now/',
//       billingCycle: '1 yr',
//       monthlyFee: '$4.99',
//       quarterlyFee: '$17.97',
//       annualFee: '$59.94',
//       renewalDay: '1',
//       renewalMonth: 'February',
//       isActive: false,
//       paymentMethod: 'Alipay',
//       plan: '',
//     },
//     {
//       name: 'primegaming',
//       label: 'Prime Gaming',
//       logo: 'prime',
//       tierName: '', // prime - 14.99mo/139yr
//       url: 'https://www.amazongames.com/en-us/support/prime-gaming/articles/what-is-prime-gaming',
//       billingCycle: '1 yr',
//       monthlyFee: '$14.99',
//       quarterlyFee: '$44.97',
//       annualFee: '$139.92',
//       renewalDay: '1',
//       renewalMonth: 'March',
//       isActive: true,
//       paymentMethod: 'Visa',
//       plan: '1 month',
//     },
//     {
//       name: 'playpass',
//       label: 'Google Play Pass',
//       logo: 'playpass',
//       tierName: '', // prime - 5.99mo / 29.99yr
//       url: 'https://play.google.com/intl/en_us/about/play-pass/',
//       billingCycle: '1 mo',
//       monthlyFee: '$5.99',
//       quarterlyFee: '$17.97',
//       annualFee: '$59.94',
//       renewalDay: '1',
//       renewalMonth: 'August',
//       isActive: false,
//       paymentMethod: 'Discover',
//       plan: '',
//     },
//     {
//       name: 'eaplay',
//       label: 'EA Play',
//       logo: 'ea',
//       tierName: '', // play - 5.99mo/39.99yr, playpro - 16.99mo/119.99yr
//       url: 'https://www.ea.com/en-us/games/ea-play',
//       billingCycle: '1 yr', // 1 mo, 1 yr
//       monthlyFee: '$5.99',
//       quarterlyFee: '$17.97',
//       annualFee: '$59.94',
//       renewalDay: '1',
//       renewalMonth: 'August',
//       isActive: false,
//       paymentMethod: 'Mastercard',
//       plan: '',
//     },
//     {
//       name: 'quest+',
//       label: 'Meta Quest+',
//       logo: 'meta',
//       tierName: 'monthly', // monthly -  7.99, yearly - 59.99
//       url: 'https://www.meta.com/questplus',
//       billingCycle: '1 yr',
//       monthlyFee: '$7.99',
//       quarterlyFee: '$23.97',
//       annualFee: '$59.94',
//       renewalDay: '1',
//       renewalMonth: 'August',
//       isActive: false,
//       paymentMethod: 'Amex',
//       plan: '',
//     },
//   ],
//   totalServices: 16,
// };


export type AvailableService = {
  name: string;
  label: string;
  logo: string;
  plan?: string;
  tierName: string;
  billingCycle: string;
  url: string;
  monthlyFee: string;
  quarterlyFee: string;
  annualFee: string;
  renewalDay: string;
  renewalMonth: string;
  isActive: boolean;
};
