openapi: 3.0.0
info:
  title: QKO Beta API
  version: 1.0.0
  description: |
    Game management API for QKO Beta.
    Handles user libraries, game metadata, and service subscriptions.

servers:
  - url: http://localhost:8080
    description: Local development

paths:
  /api/v1/health:
    get:
      tags:
        - System
      summary: Health check endpoint
      description: Returns the health status of the API
      responses:
        '200':
          description: System is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "available"
                  version:
                    type: string
                    example: "1.0.0"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "internal server error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer