import type { SpendTrackingData } from '@/features/dashboard/lib/types/service.types';

export const spendTrackingPageMockData: SpendTrackingData = {
  recurringThisMonth: [
    {
      name: 'sony',
      day: '1',
      month: 'Jan',
      year: '2025',
      onlineService: 'Playstation Network',
      title: 'Playstation Plus',
      amount: '6.66',
      billingCycle: '3 month',
      spendType: 'subscription',
      paymentMethod: 'Visa',
      isActive: true,
      mediaType: 'subscription',
    },
    {
      name: 'xbox',
      day: '15',
      month: 'Mar',
      year: '2025',
      onlineService: 'Xbox Network',
      title: 'Xbox Game Pass Ultimate',
      amount: '14.99',
      billingCycle: '1 month',
      spendType: 'subscription',
      paymentMethod: 'Mastercard',
      isActive: true,
      mediaType: 'subscription',
    },
    {
      name: 'nintendo',
      day: '1',
      month: 'Jan',
      year: '2025',
      onlineService: 'Nintendo Switch Online',
      title: 'Nintendo Switch Online',
      amount: '3.99',
      billingCycle: '1 year',
      spendType: 'subscription',
      paymentMethod: 'Visa',
      isActive: true,
      mediaType: 'subscription',
    },
    {
      name: 'apple',
      day: '1',
      month: 'Aug',
      year: '2025',
      onlineService: 'Apple Arcade',
      title: 'Apple Arcade',
      amount: '6.99',
      billingCycle: '1 month',
      spendType: 'subscription',
      paymentMethod: 'Mastercard',
      isActive: true,
      mediaType: 'subscription',
    },
    {
      name: 'steam',
      title: 'Helldivers 2',
      day: '10',
      month: 'Jan',
      year: '2025',
      onlineService: 'Steam',
      amount: '10.99',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'inGamePurchase',
    },
    {
      name: 'steam',
      title: 'Path of Exile 2',
      day: '10',
      month: 'Jan',
      year: '2025',
      onlineService: 'Steam',
      amount: '20.00',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'inGamePurchase',
    },
    {
      name: 'steam',
      title: 'Sid Meier\'s Civilization VI',
      day: '11',
      month: 'Jan',
      year: '2025',
      onlineService: 'Steam',
      amount: '19.99',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'dlc',
    },
    {
      name: 'steam',
      title: 'ELDEN RING Shadow of the Erdtree',
      day: '2',
      month: 'Jan',
      year: '2025',
      onlineService: 'Steam',
      amount: '39.99',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'dlc',
    },
    {
      name: 'nintendo',
      title: 'The Legend of Zelda: Breath of the Wild',
      day: '12',
      month: 'Jan',
      year: '2025',
      amount: '29.99',
      spendType: 'one-time',
      paymentMethod: 'Visa',
      isActive: true,
      isDigital: false,
      isWishlisted: true,
      mediaType: 'disc',
    },
    {
      name: 'physical',
      title: 'Gradius V',
      day: '20',
      month: 'Jan',
      year: '2025',
      amount: '59.99',
      spendType: 'one-time',
      paymentMethod: 'Visa',
      isDigital: false,
      isWishlisted: true,
      mediaType: 'disc',
    },
    {
      name: 'physical',
      title: 'G.Skill Trident Z5 Neo RGB DDR5-6000',
      day: '20',
      month: 'Jan',
      year: '2025',
      amount: '219.98',
      spendType: 'one-time',
      paymentMethod: 'Visa',
      isDigital: false,
      isWishlisted: true,
      mediaType: 'hardware',
    }
  ],
  oneTimeThisMonth: [],
  recurringNextMonth: [
    {
      name: 'playpass',
      day: '1',
      month: 'Feb',
      year: '2025',
      onlineService: 'Google Play Pass',
      amount: '5.99',
      billingCycle: '1 mo',
      spendType: 'subscription',
      paymentMethod: 'Mastercard',
      isActive: true,
    }
  ],
  totalSpendsThisMonth: '411.58',
  totalSpendsThisYear: '411.58',
  top5SpendsAll: [
    {
      name: 'physical',
      title: 'Gradius V',
      day: '20',
      month: 'January',
      year: '2025',
      amount: '$59.99',
      spendType: 'one-time',
      paymentMethod: 'Visa',
      isDigital: false,
      isWishlisted: true,
      mediaType: 'physical',
    },
    {
      name: 'steam',
      title: 'ELDEN RING Shadow of the Erdtree',
      day: '2',
      month: 'January',
      year: '2025',
      onlineService: 'Steam',
      amount: '$39.99',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'dlc',
    },
    {
      name: 'nintendo',
      title: 'The Legend of Zelda: Breath of the Wild',
      day: '12',
      month: 'January',
      year: '2025',
      onlineService: 'Physical',
      amount: '$29.99',
      spendType: 'one-time',
      paymentMethod: 'Visa',
      isActive: true,
      isDigital: false,
      isWishlisted: true,
      mediaType: 'physical',
    },
    {
      name: 'steam',
      title: 'Sid Meier\'s Civilization VI',
      day: '11',
      month: 'January',
      year: '2025',
      onlineService: 'Steam',
      amount: '$19.99',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'dlc',
    },
    {
      name: 'steam',
      title: 'Path of Exile 2',
      day: '10',
      month: 'January',
      year: '2025',
      onlineService: 'Steam',
      amount: '$20.00',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'inGamePurchase',
    },
  ],
  top5SpendsDigital: [
    {
      name: 'steam',
      title: 'ELDEN RING Shadow of the Erdtree',
      day: '2',
      month: 'January',
      year: '2025',
      onlineService: 'Steam',
      amount: '$39.99',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'dlc',
    },
    {
      name: 'steam',
      title: 'Path of Exile 2',
      day: '10',
      month: 'January',
      year: '2025',
      onlineService: 'Steam',
      amount: '$20.00',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'inGamePurchase',
    },
    {
      name: 'steam',
      title: 'Sid Meier\'s Civilization VI',
      day: '11',
      month: 'January',
      year: '2025',
      onlineService: 'Steam',
      amount: '$19.99',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'dlc',
    },
    {
      name: 'steam',
      title: 'Helldivers 2',
      day: '10',
      month: 'January',
      year: '2025',
      onlineService: 'Steam',
      amount: '$10.99',
      spendType: 'one-time',
      paymentMethod: 'Paypal',
      isActive: true,
      isDigital: true,
      mediaType: 'inGamePurchase',
    },
    {
      name: 'applearcade',
      day: '1',
      month: 'August',
      year: '2025',
      onlineService: 'Apple Arcade',
      amount: '$6.99',
      billingCycle: '1 mo',
      spendType: 'subscription',
      paymentMethod: 'Mastercard',
      isActive: true,
    }
  ],
  top5SpendsPhysical: [
    {
      name: 'physical',
      title: 'G.Skill Trident Z5 Neo RGB DDR5-6000',
      day: '20',
      month: 'January',
      year: '2025',
      onlineService: 'Physical',
      amount: '$219.98',
      spendType: 'one-time',
      paymentMethod: 'Visa',
      isDigital: false,
      isWishlisted: true,
      mediaType: 'hardware',
    },
    {
      name: 'physical',
      title: 'Gradius V',
      day: '20',
      month: 'January',
      year: '2025',
      amount: '$59.99',
      spendType: 'one-time',
      paymentMethod: 'Visa',
      isDigital: false,
      isWishlisted: true,
      mediaType: 'disk',
    },
    {
      name: 'nintendo',
      title: 'The Legend of Zelda: Breath of the Wild',
      day: '12',
      month: 'January',
      year: '2025',
      amount: '$29.99',
      spendType: 'one-time',
      paymentMethod: 'Visa',
      isDigital: false,
      isWishlisted: true,
      mediaType: 'disk',
    }
  ],
}
