import { type LibraryItem } from "@/features/dashboard/lib/types/page.types";

export const libraryPageMockData: LibraryItem[] = [
  {
    id: "427520",
    imageUrl: "https://i.imgur.com/lDgAyT9.jpg",
    title: "Factorio",
    favorite: false,
    dateAdded: "2024-01-01",
    diskSize: "5GB",
    digitalLocation: "Steam",
    platformVersion: "PC",
  },
  {
    id: "332330",
    imageUrl: "https://i.imgur.com/mnP42vi.jpg",
    title: "Don't Starve Together",
    favorite: false,
    dateAdded: "2024-01-01",
    diskSize: "685 MB",
    digitalLocation: "Steam",
    platformVersion: "PC",
  },
  {
    id: "646570",
    imageUrl: "https://i.imgur.com/iSnOrlw.jpg",
    title: "Slay the Spire",
    favorite: false,
    dateAdded: "2024-01-01",
    diskSize: "1.2GB",
    digitalLocation: "Steam",
    platformVersion: "PC",
  },
  {
    id: "684410",
    imageUrl: "https://i.imgur.com/3w5Q5PL.jpg",
    title: "Bridge Constructor Portal",
    favorite: false,
    dateAdded: "2024-01-01",
    diskSize: "200MB",
    digitalLocation: "Steam",
    platformVersion: "PC",
  },
  {
    id: "718670",
    imageUrl: "https://i.imgur.com/dwswpNq.jpg",
    title: "Nier Automata - Game of the Year Edition",
    favorite: true,
    platformVersion: "PS4",
    dateAdded: "2024-01-01",
    diskSize: "NA",
    physicalLocation: "Condo",
    physicalLocationType: "apartment",
    physicalSublocation: "Study bookshelf",
    physicalSublocationType: "shelf",
  },
  {
    id: "555150",
    imageUrl: "https://i.imgur.com/F2aSEb4.jpg",
    title: "The First Tree",
    favorite: false,
    dateAdded: "2024-01-01",
    digitalLocation: "Steam",
    platformVersion: "PC",
    diskSize: "2GB",
  },
];
